Исправлен баг с передачкой пачкой
Falconwatch/giga_lead pull request #11
Opened 2023-11-15 09:06 UTC by AlanSl13

Исправлен баг

purest сохранил, для примера

2023-11-15 11:37 UTC, Falconwatch requested changes

2023-11-15 11:37 UTC, Falconwatch commented on test/test_newshandler.py
> +    assert(list, type(response))
Давай ещё assert на количество ответов

2023-11-16 08:25 UTC, AlanSl13 commented on test/test_newshandler.py
> +    assert(list, type(response))
Игорь, сделал

2023-11-16 11:53 UTC, Falconwatch approved these changes

2023-11-16 11:53 UTC, merged